from os.path import dirname, join

from setuptools import setup

import pm4py


def read_file(filename):
    with open(join(dirname(__file__), filename)) as f:
        return f.read()


setup(
    name=pm4py.__name__,
    version=pm4py.__version__,
    description=pm4py.__doc__.strip(),
    long_description=read_file('README'),
    author=pm4py.__author__,
    author_email=pm4py.__author_email__,
    py_modules=[pm4py.__name__],
    include_package_data=True,
    packages=['build.lib.pm4py', 'build.lib.pm4py.algo', 'build.lib.pm4py.algo.other', 'build.lib.pm4py.algo.discovery',
              'build.lib.pm4py.algo.discovery.dfg', 'build.lib.pm4py.algo.discovery.dfg.utils',
              'build.lib.pm4py.algo.discovery.dfg.adapters', 'build.lib.pm4py.algo.discovery.dfg.adapters.pandas',
              'build.lib.pm4py.algo.discovery.dfg.versions', 'build.lib.pm4py.algo.discovery.alpha',
              'build.lib.pm4py.algo.discovery.alpha.utils', 'build.lib.pm4py.algo.discovery.alpha.versions',
              'build.lib.pm4py.algo.discovery.alpha.data_structures', 'build.lib.pm4py.algo.discovery.causal',
              'build.lib.pm4py.algo.discovery.causal.versions', 'build.lib.pm4py.algo.discovery.simple',
              'build.lib.pm4py.algo.discovery.simple.model', 'build.lib.pm4py.algo.discovery.simple.model.log',
              'build.lib.pm4py.algo.discovery.simple.model.log.versions',
              'build.lib.pm4py.algo.discovery.simple.filtering', 'build.lib.pm4py.algo.discovery.simple.filtering.log',
              'build.lib.pm4py.algo.discovery.simple.filtering.log.versions',
              'build.lib.pm4py.algo.discovery.inductive', 'build.lib.pm4py.algo.discovery.inductive.util',
              'build.lib.pm4py.algo.discovery.inductive.versions',
              'build.lib.pm4py.algo.discovery.inductive.versions.dfg',
              'build.lib.pm4py.algo.discovery.inductive.versions.dfg.util',
              'build.lib.pm4py.algo.discovery.inductive.versions.dfg.data_structures',
              'build.lib.pm4py.algo.discovery.transition_system',
              'build.lib.pm4py.algo.discovery.transition_system.util',
              'build.lib.pm4py.algo.discovery.transition_system.versions', 'build.lib.pm4py.algo.filtering',
              'build.lib.pm4py.algo.filtering.dfg', 'build.lib.pm4py.algo.filtering.log',
              'build.lib.pm4py.algo.filtering.log.cases', 'build.lib.pm4py.algo.filtering.log.paths',
              'build.lib.pm4py.algo.filtering.log.variants', 'build.lib.pm4py.algo.filtering.log.timestamp',
              'build.lib.pm4py.algo.filtering.log.attributes', 'build.lib.pm4py.algo.filtering.log.auto_filter',
              'build.lib.pm4py.algo.filtering.log.end_activities',
              'build.lib.pm4py.algo.filtering.log.start_activities', 'build.lib.pm4py.algo.filtering.common',
              'build.lib.pm4py.algo.filtering.common.timestamp', 'build.lib.pm4py.algo.filtering.common.attributes',
              'build.lib.pm4py.algo.filtering.common.end_activities',
              'build.lib.pm4py.algo.filtering.common.start_activities', 'build.lib.pm4py.algo.filtering.pandas',
              'build.lib.pm4py.algo.filtering.pandas.cases', 'build.lib.pm4py.algo.filtering.pandas.paths',
              'build.lib.pm4py.algo.filtering.pandas.variants', 'build.lib.pm4py.algo.filtering.pandas.timestamp',
              'build.lib.pm4py.algo.filtering.pandas.attributes', 'build.lib.pm4py.algo.filtering.pandas.auto_filter',
              'build.lib.pm4py.algo.filtering.pandas.end_activities',
              'build.lib.pm4py.algo.filtering.pandas.start_activities', 'build.lib.pm4py.algo.simulation',
              'build.lib.pm4py.algo.simulation.playout', 'build.lib.pm4py.algo.simulation.playout.versions',
              'build.lib.pm4py.algo.simulation.playout.data_structures',
              'build.lib.pm4py.algo.simulation.tree_generator',
              'build.lib.pm4py.algo.simulation.tree_generator.versions', 'build.lib.pm4py.algo.conformance',
              'build.lib.pm4py.algo.conformance.alignments', 'build.lib.pm4py.algo.conformance.alignments.versions',
              'build.lib.pm4py.algo.conformance.tokenreplay', 'build.lib.pm4py.algo.conformance.tokenreplay.versions',
              'build.lib.pm4py.algo.conformance.tokenreplay.diagnostics', 'build.lib.pm4py.algo.enhancement',
              'build.lib.pm4py.algo.enhancement.sna', 'build.lib.pm4py.algo.enhancement.sna.versions',
              'build.lib.pm4py.util', 'build.lib.pm4py.util.lp', 'build.lib.pm4py.util.lp.util',
              'build.lib.pm4py.util.lp.versions', 'build.lib.pm4py.objects', 'build.lib.pm4py.objects.log',
              'build.lib.pm4py.objects.log.util', 'build.lib.pm4py.objects.log.adapters',
              'build.lib.pm4py.objects.log.adapters.pandas', 'build.lib.pm4py.objects.log.exporter',
              'build.lib.pm4py.objects.log.exporter.csv', 'build.lib.pm4py.objects.log.exporter.csv.versions',
              'build.lib.pm4py.objects.log.exporter.xes', 'build.lib.pm4py.objects.log.exporter.xes.versions',
              'build.lib.pm4py.objects.log.exporter.parquet', 'build.lib.pm4py.objects.log.exporter.parquet.versions',
              'build.lib.pm4py.objects.log.importer', 'build.lib.pm4py.objects.log.importer.csv',
              'build.lib.pm4py.objects.log.importer.csv.versions', 'build.lib.pm4py.objects.log.importer.xes',
              'build.lib.pm4py.objects.log.importer.xes.versions', 'build.lib.pm4py.objects.log.importer.parquet',
              'build.lib.pm4py.objects.log.importer.parquet.versions', 'build.lib.pm4py.objects.petri',
              'build.lib.pm4py.objects.petri.common', 'build.lib.pm4py.objects.petri.exporter',
              'build.lib.pm4py.objects.petri.importer', 'build.lib.pm4py.objects.conversion',
              'build.lib.pm4py.objects.conversion.log', 'build.lib.pm4py.objects.conversion.log.versions',
              'build.lib.pm4py.objects.conversion.process_tree',
              'build.lib.pm4py.objects.conversion.process_tree.versions', 'build.lib.pm4py.objects.process_tree',
              'build.lib.pm4py.objects.random_variables', 'build.lib.pm4py.objects.random_variables.normal',
              'build.lib.pm4py.objects.random_variables.uniform', 'build.lib.pm4py.objects.random_variables.constant0',
              'build.lib.pm4py.objects.random_variables.exponential', 'build.lib.pm4py.objects.stochastic_petri',
              'build.lib.pm4py.objects.transition_system', 'build.lib.pm4py.evaluation',
              'build.lib.pm4py.evaluation.precision', 'build.lib.pm4py.evaluation.precision.versions',
              'build.lib.pm4py.evaluation.simplicity', 'build.lib.pm4py.evaluation.simplicity.versions',
              'build.lib.pm4py.evaluation.generalization', 'build.lib.pm4py.evaluation.generalization.versions',
              'build.lib.pm4py.evaluation.replay_fitness', 'build.lib.pm4py.evaluation.replay_fitness.versions',
              'build.lib.pm4py.statistics', 'build.lib.pm4py.statistics.traces',
              'build.lib.pm4py.statistics.traces.log', 'build.lib.pm4py.statistics.traces.common',
              'build.lib.pm4py.statistics.traces.pandas', 'build.lib.pm4py.visualization',
              'build.lib.pm4py.visualization.dfg', 'build.lib.pm4py.visualization.dfg.versions',
              'build.lib.pm4py.visualization.sna', 'build.lib.pm4py.visualization.sna.versions',
              'build.lib.pm4py.visualization.common', 'build.lib.pm4py.visualization.graphs',
              'build.lib.pm4py.visualization.graphs.util', 'build.lib.pm4py.visualization.graphs.versions',
              'build.lib.pm4py.visualization.petrinet', 'build.lib.pm4py.visualization.petrinet.util',
              'build.lib.pm4py.visualization.petrinet.common', 'build.lib.pm4py.visualization.petrinet.versions',
              'build.lib.pm4py.visualization.process_tree', 'build.lib.pm4py.visualization.process_tree.versions',
              'build.lib.pm4py.visualization.transition_system', 'build.lib.pm4py.visualization.transition_system.util',
              'build.lib.pm4py.visualization.transition_system.versions', 'build.lib.tests.documentation_tests',
              'pm4py', 'pm4py.algo', 'pm4py.algo.other', 'pm4py.algo.other.clustering',
              'pm4py.algo.other.clustering.versions', 'pm4py.algo.other.decisiontree',
              'pm4py.algo.other.decisiontree.applications', 'pm4py.algo.discovery', 'pm4py.algo.discovery.dfg',
              'pm4py.algo.discovery.dfg.utils', 'pm4py.algo.discovery.dfg.adapters',
              'pm4py.algo.discovery.dfg.adapters.pandas', 'pm4py.algo.discovery.dfg.versions',
              'pm4py.algo.discovery.alpha', 'pm4py.algo.discovery.alpha.utils', 'pm4py.algo.discovery.alpha.versions',
              'pm4py.algo.discovery.alpha.data_structures', 'pm4py.algo.discovery.causal',
              'pm4py.algo.discovery.causal.versions', 'pm4py.algo.discovery.simple',
              'pm4py.algo.discovery.simple.model', 'pm4py.algo.discovery.simple.model.log',
              'pm4py.algo.discovery.simple.model.log.versions', 'pm4py.algo.discovery.simple.filtering',
              'pm4py.algo.discovery.simple.filtering.log', 'pm4py.algo.discovery.simple.filtering.log.versions',
              'pm4py.algo.discovery.inductive', 'pm4py.algo.discovery.inductive.util',
              'pm4py.algo.discovery.inductive.versions', 'pm4py.algo.discovery.inductive.versions.dfg',
              'pm4py.algo.discovery.inductive.versions.dfg.util',
              'pm4py.algo.discovery.inductive.versions.dfg.data_structures', 'pm4py.algo.discovery.transition_system',
              'pm4py.algo.discovery.transition_system.util', 'pm4py.algo.discovery.transition_system.versions',
              'pm4py.algo.filtering', 'pm4py.algo.filtering.dfg', 'pm4py.algo.filtering.log',
              'pm4py.algo.filtering.log.cases', 'pm4py.algo.filtering.log.paths', 'pm4py.algo.filtering.log.variants',
              'pm4py.algo.filtering.log.timestamp', 'pm4py.algo.filtering.log.attributes',
              'pm4py.algo.filtering.log.auto_filter', 'pm4py.algo.filtering.log.end_activities',
              'pm4py.algo.filtering.log.start_activities', 'pm4py.algo.filtering.common',
              'pm4py.algo.filtering.common.timestamp', 'pm4py.algo.filtering.common.attributes',
              'pm4py.algo.filtering.common.end_activities', 'pm4py.algo.filtering.common.start_activities',
              'pm4py.algo.filtering.pandas', 'pm4py.algo.filtering.pandas.cases', 'pm4py.algo.filtering.pandas.paths',
              'pm4py.algo.filtering.pandas.variants', 'pm4py.algo.filtering.pandas.timestamp',
              'pm4py.algo.filtering.pandas.attributes', 'pm4py.algo.filtering.pandas.auto_filter',
              'pm4py.algo.filtering.pandas.end_activities', 'pm4py.algo.filtering.pandas.start_activities',
              'pm4py.algo.simulation', 'pm4py.algo.simulation.playout', 'pm4py.algo.simulation.playout.versions',
              'pm4py.algo.simulation.playout.data_structures', 'pm4py.algo.simulation.tree_generator',
              'pm4py.algo.simulation.tree_generator.versions', 'pm4py.algo.conformance',
              'pm4py.algo.conformance.alignments', 'pm4py.algo.conformance.alignments.versions',
              'pm4py.algo.conformance.tokenreplay', 'pm4py.algo.conformance.tokenreplay.versions',
              'pm4py.algo.conformance.tokenreplay.diagnostics', 'pm4py.algo.enhancement', 'pm4py.algo.enhancement.sna',
              'pm4py.algo.enhancement.sna.versions', 'pm4py.util', 'pm4py.util.lp', 'pm4py.util.lp.util',
              'pm4py.util.lp.versions', 'pm4py.objects', 'pm4py.objects.log', 'pm4py.objects.log.util',
              'pm4py.objects.log.adapters', 'pm4py.objects.log.adapters.pandas', 'pm4py.objects.log.exporter',
              'pm4py.objects.log.exporter.csv', 'pm4py.objects.log.exporter.csv.versions',
              'pm4py.objects.log.exporter.xes', 'pm4py.objects.log.exporter.xes.versions',
              'pm4py.objects.log.exporter.parquet', 'pm4py.objects.log.exporter.parquet.versions',
              'pm4py.objects.log.importer', 'pm4py.objects.log.importer.csv', 'pm4py.objects.log.importer.csv.versions',
              'pm4py.objects.log.importer.xes', 'pm4py.objects.log.importer.xes.versions',
              'pm4py.objects.log.importer.parquet', 'pm4py.objects.log.importer.parquet.versions', 'pm4py.objects.bpmn',
              'pm4py.objects.bpmn.util', 'pm4py.objects.bpmn.exporter', 'pm4py.objects.bpmn.importer',
              'pm4py.objects.petri', 'pm4py.objects.petri.common', 'pm4py.objects.petri.exporter',
              'pm4py.objects.petri.importer', 'pm4py.objects.conversion', 'pm4py.objects.conversion.log',
              'pm4py.objects.conversion.log.versions', 'pm4py.objects.conversion.process_tree',
              'pm4py.objects.conversion.process_tree.versions', 'pm4py.objects.conversion.bpmn_to_petri',
              'pm4py.objects.conversion.bpmn_to_petri.versions', 'pm4py.objects.conversion.petri_to_bpmn',
              'pm4py.objects.conversion.petri_to_bpmn.util', 'pm4py.objects.conversion.petri_to_bpmn.versions',
              'pm4py.objects.process_tree', 'pm4py.objects.random_variables', 'pm4py.objects.random_variables.normal',
              'pm4py.objects.random_variables.uniform', 'pm4py.objects.random_variables.constant0',
              'pm4py.objects.random_variables.exponential', 'pm4py.objects.stochastic_petri',
              'pm4py.objects.transition_system', 'pm4py.evaluation', 'pm4py.evaluation.precision',
              'pm4py.evaluation.precision.versions', 'pm4py.evaluation.simplicity',
              'pm4py.evaluation.simplicity.versions', 'pm4py.evaluation.generalization',
              'pm4py.evaluation.generalization.versions', 'pm4py.evaluation.replay_fitness',
              'pm4py.evaluation.replay_fitness.versions', 'pm4py.statistics', 'pm4py.statistics.traces',
              'pm4py.statistics.traces.log', 'pm4py.statistics.traces.common', 'pm4py.statistics.traces.pandas',
              'pm4py.visualization', 'pm4py.visualization.dfg', 'pm4py.visualization.dfg.versions',
              'pm4py.visualization.sna', 'pm4py.visualization.sna.versions', 'pm4py.visualization.bpmn',
              'pm4py.visualization.bpmn.util', 'pm4py.visualization.bpmn.versions', 'pm4py.visualization.common',
              'pm4py.visualization.graphs', 'pm4py.visualization.graphs.util', 'pm4py.visualization.graphs.versions',
              'pm4py.visualization.petrinet', 'pm4py.visualization.petrinet.util',
              'pm4py.visualization.petrinet.common', 'pm4py.visualization.petrinet.versions',
              'pm4py.visualization.decisiontree', 'pm4py.visualization.decisiontree.versions',
              'pm4py.visualization.process_tree', 'pm4py.visualization.process_tree.versions',
              'pm4py.visualization.transition_system', 'pm4py.visualization.transition_system.util',
              'pm4py.visualization.transition_system.versions', 'tests.documentation_tests'],
    url='http://www.pm4py.org',
    license='GPL 3.0',
    install_requires=[
        'pyvis',
        'networkx>=2.2',
        'matplotlib==2.2.2',
        'numpy',
        'ciso8601',
        'cvxopt',
        'lxml',
        'graphviz',
        'pyarrow',
        'pandas>=0.24.1',
        'scipy',
        'scikit-learn',
        'pydotplus',
        'bpmn_python==0.0.18',
        'pulp',
        'pytz>=2018.9'
    ],
    project_urls={
        'Documentation': 'http://pm4py.pads.rwth-aachen.de/documentation/',
        'Source': 'https://github.com/pm4py/pm4py-source',
        'Tracker': 'https://github.com/pm4py/pm4py-source/issues',
    }
)
